#!/usr/bin/env python3
"""Build the user-facing Evidence Lab skill catalogue from reviewed copy and pack metadata."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "catalog" / "skill-docs.json"
BUNDLE_META = ROOT / "packs" / "core" / "evidence-lab-research" / "meta.json"
OUTPUT = ROOT / "docs" / "skills.md"

STATUS_LABELS = {
    "needs-substantive-work": "Needs substantive work",
    "needs-representative-testing": "Needs representative run",
    "review-ready": "Review ready",
    "production": "Production accepted",
}


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def canonical_skills() -> dict[str, dict]:
    result: dict[str, dict] = {}
    for meta_path in sorted((ROOT / "packs").glob("*/*/meta.json")):
        pack_root = meta_path.parent
        pack = load(pack_root / "pack.json")
        meta = load(meta_path)
        if pack.get("distribution_bundle", False) or meta.get("status") in {"reference", "deprecated"}:
            continue
        for skill in meta.get("skills", []):
            name = skill["name"]
            if skill["quality_status"] == "support-only" or name == "evidence-lab-onboarding":
                continue
            if name in result:
                raise ValueError(f"duplicate canonical skill: {name}")
            skill_path = pack_root / "skills" / name / "SKILL.md"
            if not skill_path.is_file():
                raise ValueError(f"missing SKILL.md for {name}")
            result[name] = {
                "pack_id": pack["id"],
                "pack_readme": (pack_root / "README.md").relative_to(ROOT).as_posix(),
                "path": skill_path.relative_to(ROOT).as_posix(),
                "quality_status": skill["quality_status"],
            }
    return result


def validate(config: dict, canonical: dict[str, dict]) -> None:
    group_ids = [group["id"] for group in config["groups"]]
    if len(group_ids) != len(set(group_ids)):
        raise ValueError("duplicate documentation group ID")
    items = config["skills"]
    item_ids = [item["id"] for item in items]
    if len(item_ids) != len(set(item_ids)):
        raise ValueError("duplicate documented skill ID")
    unknown_groups = sorted({item["group"] for item in items} - set(group_ids))
    if unknown_groups:
        raise ValueError(f"unknown documentation groups: {unknown_groups}")
    bundled = {item["name"] for item in load(BUNDLE_META)["skills"]}
    if set(item_ids) != bundled:
        raise ValueError(f"documented skills do not match bundle: documented={sorted(item_ids)}, bundled={sorted(bundled)}")
    if set(item_ids) != set(canonical):
        raise ValueError("documented skills do not match canonical published skill sources")


def link_to(path: str) -> str:
    return f"../{path}"


def render(config: dict, canonical: dict[str, dict]) -> str:
    items = {item["id"]: item for item in config["skills"]}
    counts: dict[str, int] = {}
    for info in canonical.values():
        status = info["quality_status"]
        counts[status] = counts.get(status, 0) + 1

    lines = [
        "# Evidence Lab skill catalogue",
        "",
        "<!-- Generated by scripts/build_skill_docs.py from catalog/skill-docs.json and canonical pack metadata. -->",
        "",
        "This page helps you choose a skill by the research result you need. You do not need to understand the pack layout or invoke a skill by name: describe your task naturally and Codex or Claude Code can route to the relevant procedure.",
        "",
        "New here? Start with the [two-minute installation guide](getting-started.md). Want every skill at once? Install `evidence-lab-research@evidence-lab-plugins`.",
        "",
        "## Choose by outcome",
        "",
        "| I need to… | Start with |",
        "|---|---|",
        "| Find papers or verify a reference | [`paper-lookup`](#paper-lookup) or [`citation-management`](#citation-management) |",
        "| Build a literature or systematic review | [`literature-review`](#literature-review) or [`systematic-review`](#systematic-review) |",
        "| Turn an idea into a study plan | [`hypothesis-generation`](#hypothesis-generation), then [`experimental-design`](#experimental-design) |",
        "| Decide how much data to collect | [`statistical-power`](#statistical-power) |",
        "| Inspect or analyze a dataset | [`exploratory-data-analysis`](#exploratory-data-analysis), then [`statistical-analysis`](#statistical-analysis) |",
        "| Analyze interviews or open responses | [`qualitative-analysis`](#qualitative-analysis) |",
        "| Inspect scientific images | [`research-image-analysis`](#research-image-analysis) |",
        "| Write or review a manuscript | [`writing-skill`](#writing-skill), [`peer-review`](#peer-review), or [`latex-and-venue-formatting`](#latex-and-venue-formatting) |",
        "| Convert source files to Markdown | [`markitdown`](#markitdown) |",
        "| Save my own recurring workflow | [`personal-skill-authoring`](#personal-skill-authoring) |",
        "",
        "## Readiness at a glance",
        "",
        f"The installable bundle contains **{len(canonical)} skills**: **{counts.get('needs-representative-testing', 0)} need a representative run** and **{counts.get('needs-substantive-work', 0)} need substantive work**. Installation readiness and scientific acceptance are separate: a skill can install correctly while still awaiting real-task review.",
        "",
        "- **Needs representative run:** the procedure and checks exist, but a reviewer still needs to run it on representative research material.",
        "- **Needs substantive work:** important method content or acceptance evidence is still missing; treat the skill as experimental.",
        "- See the generated [readiness inventory](skill-pack-readiness.md) for pack-level evidence and exact status counts.",
        "",
    ]

    for group in config["groups"]:
        lines.extend([
            f"## {group['title']}",
            "",
            group["description"],
            "",
            "| Skill | Use it when… | Produces | Source pack | Readiness |",
            "|---|---|---|---|---|",
        ])
        for skill_id in [item["id"] for item in config["skills"] if item["group"] == group["id"]]:
            item = items[skill_id]
            info = canonical[skill_id]
            status = STATUS_LABELS.get(info["quality_status"], info["quality_status"])
            lines.append(
                f"| <a id=\"{skill_id}\"></a>[`{skill_id}`]({link_to(info['path'])}) | "
                f"{item['use_when']} | {item['produces']} | "
                f"[`{info['pack_id']}`]({link_to(info['pack_readme'])}) | {status} |"
            )
        lines.append("")

    lines.extend([
        "## What you will find inside a skill",
        "",
        "Each skill link above opens its canonical `SKILL.md`, the procedure the agent reads when the skill is selected. A skill directory may also contain:",
        "",
        "- `scripts/` for deterministic calculations, conversion, validation, or rendering;",
        "- `references/` for standards, long examples, and method details loaded only when needed;",
        "- `templates/` or `assets/` for reusable output material;",
        "- `evals/` for positive and negative routing cases.",
        "",
        "The one-install plugin contains generated copies, while the focused pack paths linked here remain the canonical sources for review and contribution.",
        "",
        "## Deliberately not included",
        "",
        "The all-in-one research plugin does not include the optional onboarding skill, compatibility-only routers, unpublished reference packs, or private project data. Onboarding remains available separately through `evidence-lab-core`.",
        "",
        "Continue with [Getting started](getting-started.md), return to the [documentation home](README.md), or inspect [how packs and generated copies relate](architecture.md).",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    config = load(CONFIG)
    canonical = canonical_skills()
    validate(config, canonical)
    rendered = render(config, canonical)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"FAIL: generated skill catalogue is stale: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"verified {OUTPUT.relative_to(ROOT)} with {len(canonical)} skills")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} with {len(canonical)} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
