#!/usr/bin/env python3
"""Scaffold a new host-neutral pack from templates/pack.

    python3 scripts/new_pack.py systematic-review --layer workflow --skill screening --owner Tim --reviewer Misha

Creates packs/<layer>/<name>/ with one shared skill and review metadata. Host
manifests are generated by scripts/build_adapters.py.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "templates" / "pack"
PACKS = ROOT / "packs"

PLACEHOLDERS = ("__PLUGIN__", "__SKILL__", "__OWNER__", "__REVIEWER__", "__DATE__", "__LAYER__")
LAYER_DIRS = {"core": "core", "workflow": "workflows", "domain": "domains", "local": "local"}
NAME_RE = re.compile(r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$")


def render(text: str, values: dict[str, str]) -> str:
    for key in PLACEHOLDERS:
        text = text.replace(key, values[key])
    return text


def validate_name(value: str, label: str) -> None:
    if not NAME_RE.fullmatch(value):
        raise ValueError(f"{label} must be kebab-case using lowercase letters, digits, and hyphens")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("name", help="pack name, kebab-case")
    ap.add_argument("--layer", choices=sorted(LAYER_DIRS), required=True)
    ap.add_argument("--skill", required=True, help="name of the first skill, kebab-case")
    ap.add_argument("--owner", required=True)
    ap.add_argument("--reviewer", required=True)
    args = ap.parse_args()

    try:
        validate_name(args.name, "pack name")
        validate_name(args.skill, "skill name")
    except ValueError as exc:
        print(f"FAIL: {exc}")
        return 2

    target = PACKS / LAYER_DIRS[args.layer] / args.name
    if target.exists():
        print(f"FAIL: {target.relative_to(ROOT)} already exists")
        return 1

    values = {
        "__PLUGIN__": args.name,
        "__SKILL__": args.skill,
        "__OWNER__": args.owner,
        "__REVIEWER__": args.reviewer,
        "__DATE__": date.today().isoformat(),
        "__LAYER__": args.layer,
    }

    for src in sorted(TEMPLATE.rglob("*")):
        rel = Path(render(str(src.relative_to(TEMPLATE)), values))
        dst = target / rel
        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.suffix in {".md", ".json", ".py", ".sh"}:
            dst.write_text(render(src.read_text(encoding="utf-8"), values), encoding="utf-8")
            shutil.copymode(src, dst)
        else:
            shutil.copy2(src, dst)

    print(f"created {target.relative_to(ROOT)}")
    print("next: write the procedure, fill the eval set, run scripts/build_adapters.py, then verify")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
